### ISSUE TITLE
[BUG] Readme does not list mod dependencies

### ISSUE THREAD

**Issue by serenewaffles** [FluffierThanThou/ColonyManager#125]
Per [Issue 124](https://github.com/FluffierThanThou/ColonyManager/issues/124), properly displaying research options requires the user also have [ResearchTree](https://github.com/FluffierThanThou/ResearchTree) installed. The Readme and installation instructions should mention the requirement.

**Comment by tmajibon** [comment]
Technically not a dependency, you can still use it and the research options are usable... just not pretty.

Still, might be worthwhile to acknowledge, can't hurt to add a line of "As this game adds research options, a research tab mod like ResearchTree or [ResearchPal](https://github.com/notfood/RimWorld-ResearchPal/releases) is recommended."

Just fyi, all mods that add research options have issues, it's one area of the mod api that's sorely lacking and a research tab mod is recommended anytime you add items to the research tree because otherwise there's no way to prevent them from overlapping or really guarantee that they'll look decent at all.

**Comment by serenewaffles** [comment]
Please see [RT Fuse](https://github.com/Ratysz/RT_Fuse) for an example of a mod that adds research options, doesn't require another mod to display research options, and has a readable layout.
