### ISSUE TITLE
Colony.Manager.rar is not RAR archive

### ISSUE THREAD

**Issue by LeetCodes** [FluffierThanThou/ColonyManager#82]
> Michaels-iMac:Downloads michael$ unrar x Colony.Manager.rar 
> 
> UNRAR 5.50 beta 3 freeware      Copyright (c) 1993-2017 Alexander Roshal
> 
> Colony.Manager.rar is not RAR archive
> No files to extract

seems like a weird issue but couldn't extract any of your .rar's on OS X, had to rename from .rar to .zip, tried extracting with keka and unrar binary, after changing file extension to .zip it extracted without issue, same with your other .rar's, StackMerger, FollowMe and WorkTab as far as i've tested, i had to rename them all from .rar to .zip, but your Work Tab v0.17.0.2 zip extracted fine, but it wasn't a rar like your other mod releases
keka gave the following error

> Error code 10 using "unrar"
> No files matching the mask

**Comment by FluffierThanThou** [comment]
Yep, this was a problem with my build script. Like you found out, I fixed it before the latest release of WorkTab, all my older releases still have this problem. Since some unzippers auto-detect the correct format, and it's a simple fix anyway, I decided not to update the releases as is. 

New releases will all be correctly .zip files.
