### ISSUE TITLE
Construction tab

### ISSUE THREAD

**Issue by Danomano** [FluffierThanThou/ColonyManager#89]
First up I know this isn't an 'issue,' but I know this feature has been pulled recently, I'm not sure why that is so of someone wants to fill me in feel free. The construction tab was a pretty powerful feature, and was almost necessary if a colony is running 50+ production benches. I'm not new to coding so so I'm happy to offer help.

**Comment by FluffierThanThou** [comment]
Three main reasons;

_changes to job system_; a lot of the underlying vanilla code was changed, so the production tab would have to be a significant rewrite. 

_lingering bugs_; Colony Manager is due for a rewrite anyway, as my programming skills have moved on quite a bit from the time that I first laid the groundwork for Colony Manager. This is especially obvious in some of the production tab code, which - to put it mildly - is fairly horrendous. It also has some unresolved issues and bugs that I have not been able to trace (replicating bills, ingredient count calculation for ingredient bill picker).

_feature creep_; a lot of the functions of the production tab were added in a rather clumsy fashion, and would have been much better placed in a dedicated mod that expands the 'normal' bill interface. 

Because of these, my initial plan was to make a quick update of Colony Manager for the hunting/foraging/etc. tabs of the mod, and break out the production part to a dedicated mod later on. What ended up happening is that someone else made a bill mod that largely had the functionality I wanted to add (https://ludeon.com/forums/index.php?topic=33083.0), so I saw no further point in creating a new mod.
